spring:
  application:
    name: data
  profiles:
      active: dev
  redis:
    port: 6379
    host: localhost
    password:
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mq:
  defaultExchange: actExchange
  queue: queue
  routeKey: queue_key