server:
  port: 80
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 启用自动根据服务ID生成路由 开启注册中心自动路由功能
          lower-case-service-id: true # 设置路由的路径为小写的服务ID 默认是大写
      routes:
        - id: news-router
          uri: http://localhost:8082/
          predicates:
            - Path=/seckill/**
          filters:
            - StripPrefix=1
        - id: order-router
          uri: http://localhost:8081/
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: user-router
          uri: http://localhost:8083/
          predicates:
            - Path=/seuser/**
          filters:
            - StripPrefix=1
        - id: auth-router
          uri: http://localhost:8084/
          predicates:
            - Path=/oauth/**
#          filters:
#            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          # 配置RSA的公钥访问地址
          jwk-set-uri: 'http://localhost:80/oauth/rsa/publicKey'
  redis:
    database: 0
    port: 6379
    host: localhost
    password:
# 放行白名单
secure:
  ignore:
    urls:
      - "/actuator/**"
      - "/user/login"
      - "/oauth/rsa/publicKey"
      - "/oauth/oauth/token"
      - "/oauth/token"
      - "/seuser/user/register"
      - "/seuser/user/login"